allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
fetchTimeout: 600000
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
